services:
  - type: web
    name: maternal-health-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000

  # - type: worker
  #   name: whatsapp-bot
  #   env: python
  #   plan: free
  #   rootDir: whatsapp-bot
  #   buildCommand: pip install -r requirements.txt
  #   startCommand: python app.py
